stroka = input("Введите строку:")
print(stroka[2])
print(stroka[-1])
print(stroka[:5])
print(stroka[:len(stroka)-2])
print(stroka[::2])
print(stroka[1::2])
print(stroka[::-1])
print(stroka[::-2])
print(len(stroka))